name: Deploy Prod Lambda

on:
    push:
        branches: [main]
        paths:
            - "lambda/**"
            - ".github/workflows/aws-lambda-entry-prod.yml"

jobs:
    deploy:
        uses: ./.github/workflows/aws-lambda-deploy.yml
        with:
            branch: main
            function_name: prod-lambda
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
